#ifndef HARDWARE_PORT_DEFINITIONS_H
#define HARDWARE_PORT_DEFINITIONS_H

//CAN Jaguar IDs (1-8)

#define DRIVE_TRAIN_RIGHT_MOTOR 1
#define SHOOTER_SUPPORT_MOTOR 2
#define UNUSED_JAG_1 3
#define SHOOTER_ELEVATING_MOTOR 4
#define SHOOTER_PRIMARY_MOTOR 5
#define DRIVE_TRAIN_LEFT_MOTOR 6
#define UNUSED_JAG_2 7
#define UNUSED_JAG_3 8
#endif
