#ifndef JOYSTICK_BUTTON_SHEET_H
#define JOYSTICK_BUTTON_SHEET_H

//left drive stick
#define LEFT_DASHBOARD_PULL_SHOOTER_DATA_BTN 6
#define LEFT_DRIVE_TRAIN_CHANGE_DRIVE_BTN 10
#define LEFT_DRIVE_TRAIN_TURBO_ON_BTN 1
#define LEFT_DASHBOARD_WRITE_DRIVE_DATA_BTN 11
//right drive stick
#define RIGHT_DRIVE_TRAIN_TURBO_ON_BTN 1
#define RIGHT_CLIMBER_SAFTEY 2
//operator stick
#define OPERATOR_SHOOTER_AUTOAIM_BTN 2
#define OPERATOR_CLIMBER_CHAINSAW_DOWN_BTN 7
#define OPERATOR_CLIMBER_CHAINSAW_MIDDLE_BTN 6
#define OPERATOR_CLIMBER_CHAINSAW_UP_BTN 5
#define OPERATOR_CLIMBER_ENGAGE_BTN 11
#define OPERATOR_CLIMBER_DISENGAGE_BTN 12
#define OPERATOR_SHOOTER_ON_BTN 9
#define OPERATOR_SHOOTER_OFF_BTN 10
#define OPERATOR_SHOOTER_SHOOT_BTN 1
#endif

