#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousForward.h"
#include "Commands/AutonomousSequence.h"
#include "Commands/AutonomousTurns.h"
#include "Commands/ClimberDrive.h"
#include "Commands/ClimberOff.h"
#include "Commands/ClimberOn.h"
#include "Commands/CollectorSendDiscCount.h"
#include "Commands/DiscsReverse.h"
#include "Commands/EngageClimber.h"
#include "Commands/JoystickDrive.h"
#include "Commands/PullShooterData.h"
#include "Commands/SetChainsawPosition1.h"
#include "Commands/SetChainsawPosition2.h"
#include "Commands/SetChainsawPosition3.h"
#include "Commands/SetCubicDrive.h"
#include "Commands/SetShooterToCalculatedValues.h"
#include "Commands/Shoot.h"
#include "Commands/ShooterOff.h"
#include "Commands/ShooterOn.h"
#include "Commands/TurboDriveOn.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/WriteDriveData.h"
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	operatorStick = new SmartJoystick(1);
	
	engageAutoAim = new JoystickButton(operatorStick, 2);
	engageAutoAim->WhileHeld(new SetShooterToCalculatedValues());
	chainsawPos3 = new JoystickButton(operatorStick, 7);
	chainsawPos3->WhenPressed(new SetChainsawPosition3());
	chainsawPos2 = new JoystickButton(operatorStick, 6);
	chainsawPos2->WhenPressed(new SetChainsawPosition2());
	chainsawPos1 = new JoystickButton(operatorStick, 5);
	chainsawPos1->WhenPressed(new SetChainsawPosition1());
	climberDisengage = new JoystickButton(operatorStick, 12);
	climberDisengage->WhenPressed(new ClimberOff());
	climberEngage = new JoystickButton(operatorStick, 11);
	climberEngage->WhenPressed(new ClimberOn());
	shooterOffButton = new JoystickButton(operatorStick, 10);
	shooterOffButton->WhenPressed(new ShooterOff());
	shooterOnButton = new JoystickButton(operatorStick, 9);
	shooterOnButton->WhenPressed(new ShooterOn());
	shootButton = new JoystickButton(operatorStick, 1);
	shootButton->WhenPressed(new Shoot());
	rightStick = new SmartJoystick(3);
	
	rightTurboOn = new JoystickButton(rightStick, 1);
	rightTurboOn->WhileHeld(new TurboDriveOn());
	leftStick = new SmartJoystick(2);
	
	pullShooterDashData = new JoystickButton(leftStick, 6);
	pullShooterDashData->WhenPressed(new PullShooterData());
	switchDrive = new JoystickButton(leftStick, 10);
	switchDrive->WhenPressed(new SetCubicDrive());
	leftTurboOn = new JoystickButton(leftStick, 1);
	leftTurboOn->WhileHeld(new TurboDriveOn());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("CollectorSendDiscCount", new CollectorSendDiscCount());
	SmartDashboard::PutData("Autonomous Turns", new AutonomousTurns());
	SmartDashboard::PutData("ShooterOn", new ShooterOn());
	SmartDashboard::PutData("ShooterOff", new ShooterOff());
	SmartDashboard::PutData("ClimberOn", new ClimberOn());
	SmartDashboard::PutData("ClimberOff", new ClimberOff());
	SmartDashboard::PutData("TurboDriveOn", new TurboDriveOn());
	SmartDashboard::PutData("SetCubicDrive", new SetCubicDrive());
	SmartDashboard::PutData("SetChainsawPosition1", new SetChainsawPosition1());
	SmartDashboard::PutData("SetChainsawPosition2", new SetChainsawPosition2());
	SmartDashboard::PutData("PullShooterData", new PullShooterData());
	SmartDashboard::PutData("SetChainsawPosition3", new SetChainsawPosition3());
	SmartDashboard::PutData("ClimberDrive", new ClimberDrive());
	SmartDashboard::PutData("EngageClimber", new EngageClimber());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	writeDriveDataButton = new JoystickButton(leftStick, 11);
	writeDriveDataButton->WhileHeld(new WriteDriveData());
	rightStick->ToggleInvertYAxis();
}
SmartJoystick* OI::getOperatorStick() {
	return operatorStick;
}
SmartJoystick* OI::getRightStick() {
	return rightStick;
}
SmartJoystick* OI::getLeftStick() {
	return leftStick;
}