#ifndef OI_H
#define OI_H
#include "WPILib.h"
class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* operatorStick;
	JoystickButton* engageAutoAim;
	JoystickButton* chainsawPos3;
	JoystickButton* chainsawPos2;
	JoystickButton* chainsawPos1;
	JoystickButton* climberDisengage;
	JoystickButton* climberEngage;
	JoystickButton* shooterOffButton;
	JoystickButton* shooterOnButton;
	JoystickButton* shootButton;
	Joystick* rightStick;
	JoystickButton* rightTurboOn;
	Joystick* leftStick;
	JoystickButton* pullShooterDashData;
	JoystickButton* switchDrive;
	JoystickButton* leftTurboOn;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	JoystickButton* writeDriveDataButton;
public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	Joystick* getLeftStick();
	Joystick* getRightStick();
	Joystick* getOperatorStick();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};
#endif
