#ifndef OI_H
#define OI_H
#include "WPILib.h"
class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* operatorStick;
	JoystickButton* climberDisengage;
	JoystickButton* climberEngage;
	JoystickButton* climberDown;
	JoystickButton* climberUp;
	JoystickButton* testSmartDashboard;
	JoystickButton* shooterOffButton;
	JoystickButton* shooterOnButton;
	JoystickButton* shootButton;
	Joystick* rightStick;
	Joystick* leftStick;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	JoystickButton* writeDriveDataButton;
public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	Joystick* getLeftStick();
	Joystick* getRightStick();
	Joystick* getOperatorStick();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};
#endif
