#ifndef OI_H
#define OI_H
#include "WPILib.h"
#include "WPILibExtensions/WPILibExtensions.h"
class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SmartJoystick* operatorStick;
	JoystickButton* engageAutoAim;
	JoystickButton* chainsawPos3;
	JoystickButton* chainsawPos2;
	JoystickButton* chainsawPos1;
	JoystickButton* climberDisengage;
	JoystickButton* climberEngage;
	JoystickButton* shooterOffButton;
	JoystickButton* shooterOnButton;
	JoystickButton* shootButton;
	SmartJoystick* rightStick;
	JoystickButton* rightTurboOn;
	SmartJoystick* leftStick;
	JoystickButton* pullShooterDashData;
	JoystickButton* switchDrive;
	JoystickButton* leftTurboOn;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	JoystickButton* writeDriveDataButton;
public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	SmartJoystick* getLeftStick();
	SmartJoystick* getRightStick();
	SmartJoystick* getOperatorStick();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};
#endif
