Version 0.0.2

---
Name: robot13
Base: Robot
Children:
- Name: Subsystems
  Base: Subsystems
  Children:
  - Name: Climber
    Base: Subsystem
    Children: []
    Properties:
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
  - Name: DriveTrain
    Base: Subsystem
    Children:
    - Name: LeftDriveMotor
      Base: CAN Jaguar
      Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: &id001 ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']
          default: '2'
          name: CAN ID
          validators: &id002 [CANID]
          value: '2'
    - Name: RightDriveMotor
      Base: CAN Jaguar
      Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: '2'
          name: CAN ID
          validators: *id002
          value: '3'
    Properties:
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: JoystickDrive}
  - Name: Collector
    Base: Subsystem
    Children: []
    Properties:
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
  - Name: Shooter
    Base: Subsystem
    Children:
    - Name: ShooterJag
      Base: CAN Jaguar
      Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: '2'
          name: CAN ID
          validators: *id002
          value: '5'
    - Name: ShooterEncoder
      Base: Quadrature Encoder
      Children: []
      Properties:
        Channel B Module (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: ['1', '2']
          default: '1'
          name: Channel B Module (Digital)
          validators: [DigitalChannel]
          value: '1'
        Channel A Module (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: ['1', '2']
          default: '1'
          name: Channel A Module (Digital)
          validators: [DigitalChannel]
          value: '1'
        PID Source: !!robotbuilder.data.properties.ChoicesProperty
          choices: [kDistance, kRate]
          default: kRate
          name: PID Source
          validators: null
          value: kRate
        Distance Per Pulse: !!robotbuilder.data.properties.DoubleProperty {default: 1,
          name: Distance Per Pulse, validators: null, value: 1.0}
        Encoding Type: !!robotbuilder.data.properties.ChoicesProperty
          choices: [k4X, k2X, k1X]
          default: k4X
          name: Encoding Type
          validators: null
          value: k4X
        Channel B Channel (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
            '13', '14']
          default: '1'
          name: Channel B Channel (Digital)
          validators: [DigitalChannel]
          value: '2'
        Channel A Channel (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
            '13', '14']
          default: '1'
          name: Channel A Channel (Digital)
          validators: [DigitalChannel]
          value: '1'
        Reverse Direction: !!robotbuilder.data.properties.BooleanProperty {default: false,
          name: Reverse Direction, validators: null, value: false}
    Properties:
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
  Properties: {}
- Name: Operator Interface
  Base: OI
  Children:
  - Name: LeftStick
    Base: Joystick
    Children: []
    Properties:
      Number: !!robotbuilder.data.properties.ChoicesProperty
        choices: &id003 ['1', '2', '3', '4']
        default: 1
        name: Number
        validators: &id004 [Joystick]
        value: '1'
  - Name: RightStick
    Base: Joystick
    Children: []
    Properties:
      Number: !!robotbuilder.data.properties.ChoicesProperty
        choices: *id003
        default: 1
        name: Number
        validators: *id004
        value: '2'
  - Name: 'OperatorStick '
    Base: Joystick
    Children:
    - Name: ShootButton
      Base: Joystick Button
      Children: []
      Properties:
        Command: !!robotbuilder.data.properties.TypeSelectionProperty
          default: None
          name: Command
          type: Command
          validators: &id005 [TypeDropdownSelected]
          value: Shoot
        Button: !!robotbuilder.data.properties.ChoicesProperty
          choices: &id006 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
            '12']
          default: '1'
          name: Button
          validators: null
          value: '1'
        Joystick: !!robotbuilder.data.properties.ParentProperty {default: parent,
          name: Joystick, validators: null, value: 'OperatorStick '}
        When to Run: !!robotbuilder.data.properties.ChoicesProperty
          choices: &id007 [whileHeld, whenPressed, whenReleased]
          default: whileHeld
          name: When to Run
          validators: null
          value: whenPressed
    - Name: ShooterOnButton
      Base: Joystick Button
      Children: []
      Properties:
        Command: !!robotbuilder.data.properties.TypeSelectionProperty
          default: None
          name: Command
          type: Command
          validators: *id005
          value: ShooterOn
        Button: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id006
          default: '1'
          name: Button
          validators: null
          value: '5'
        Joystick: !!robotbuilder.data.properties.ParentProperty {default: parent,
          name: Joystick, validators: null, value: 'OperatorStick '}
        When to Run: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id007
          default: whileHeld
          name: When to Run
          validators: null
          value: whenPressed
    - Name: ShooterOffButton
      Base: Joystick Button
      Children: []
      Properties:
        Command: !!robotbuilder.data.properties.TypeSelectionProperty
          default: None
          name: Command
          type: Command
          validators: *id005
          value: ShooterOff
        Button: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id006
          default: '1'
          name: Button
          validators: null
          value: '6'
        Joystick: !!robotbuilder.data.properties.ParentProperty {default: parent,
          name: Joystick, validators: null, value: 'OperatorStick '}
        When to Run: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id007
          default: whileHeld
          name: When to Run
          validators: null
          value: whenPressed
    - Name: TestSmartDashboard
      Base: Joystick Button
      Children: []
      Properties:
        Command: !!robotbuilder.data.properties.TypeSelectionProperty
          default: None
          name: Command
          type: Command
          validators: *id005
          value: TestSmartDashboard
        Button: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id006
          default: '1'
          name: Button
          validators: null
          value: '8'
        Joystick: !!robotbuilder.data.properties.ParentProperty {default: parent,
          name: Joystick, validators: null, value: 'OperatorStick '}
        When to Run: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id007
          default: whileHeld
          name: When to Run
          validators: null
          value: whenPressed
    Properties:
      Number: !!robotbuilder.data.properties.ChoicesProperty
        choices: *id003
        default: 1
        name: Number
        validators: *id004
        value: '3'
  Properties: {}
- Name: Commands
  Base: Commands
  Children:
  - Name: Autonomous Command
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: None}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
  - Name: JoystickDrive
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: DriveTrain}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
  - Name: Shoot
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Shooter}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
  - Name: CollectDiscs
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Collector}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
  - Name: DiscsReverse
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Collector}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
  - Name: ShooterOn
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Shooter}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
  - Name: ShooterOff
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Shooter}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
  - Name: TestSmartDashboard
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: None}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
  Properties: {}
Properties:
  Autonomous Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
    name: Autonomous Command, type: Command, validators: null, value: Autonomous Command}
  Wiring File: !!robotbuilder.data.properties.FileProperty {default: '', extension: html,
    folder: false, name: Wiring File, validators: null, value: 'C:\WindRiver\workspace\robot13\WiringTable.html'}
  C++ Windriver Workspace: !!robotbuilder.data.properties.FileProperty {default: 'C:\Windriver\workspace',
    extension: null, folder: true, name: C++ Windriver Workspace, validators: null,
    value: 'C:\Windriver\workspace'}
  Use Default Java Package: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Use Default Java Package, validators: null, value: true}
  Java Package: !!robotbuilder.data.properties.StringProperty {default: org.usfirst.frc0000,
    name: Java Package, validators: null, value: org.usfirst.frc0000}
  Export Subsystems: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Subsystems, validators: null, value: true}
  Team Number: !!robotbuilder.data.properties.IntegerProperty {default: 0, name: Team Number,
    validators: null, value: 1073}
  Export Commands: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Commands, validators: null, value: true}
  Java Project Directory: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\Greg\NetBeansProjects',
    extension: null, folder: true, name: Java Project Directory, validators: null,
    value: 'C:\Users\Infern0\workspace'}
