// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "AutonomousForward.h"

#define FORWARD_SPEED 100
#define DISTANCE 150


AutonomousForward::AutonomousForward() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::autonomous);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void AutonomousForward::Initialize() {
	Robot::driveTrain->GetPosition(startingLeft, startingRight);
	Robot::driveTrain->Move(FORWARD_SPEED, FORWARD_SPEED);
			
	
}
// Called repeatedly when this Command is scheduled to run
void AutonomousForward::Execute() {
	
}
// Make this return true when his Command no longer needs to run execute()
bool AutonomousForward::IsFinished() {
	float currentLeft = 0;
	float currentRight= 0;
	Robot::driveTrain->GetPosition(currentLeft, currentRight);
	if ((currentLeft - startingLeft > DISTANCE) && (currentRight - startingRight > DISTANCE))
			return true;
	return false;
}
// Called once after isFinished returns true
void AutonomousForward::End() {
	Robot::driveTrain->Move(0, 0);
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousForward::Interrupted() {
}
