#include "AutonomousCommand.h"
AutonomousCommand::AutonomousCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void AutonomousCommand::Initialize() {
	
}
void AutonomousCommand::Execute() {
	
}
bool AutonomousCommand::IsFinished() {
	return false;
}
void AutonomousCommand::End() {
	
}
void AutonomousCommand::Interrupted() {
}
