#include "AutonomousTurnLeft.h"
#define FORWARD_SPEED 100
#define TURNING_ANGLE -90
AutonomousTurnLeft::AutonomousTurnLeft() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void AutonomousTurnLeft::Initialize() {
	Robot::driveTrain->Move(0, FORWARD_SPEED);
	
}
// Called repeatedly when this Command is scheduled to run
void AutonomousTurnLeft::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool AutonomousTurnLeft::IsFinished() {
	float currentAngle = Robot::driveTrain->GetGyroAngle();
	if (currentAngle - startingAngle > TURNING_ANGLE)
		return true;
	return false;
}
// Called once after isFinished returns true
void AutonomousTurnLeft::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousTurnLeft::Interrupted() {
}
