#include "AutonomousForward.h"
#define FORWARD_SPEED .5 //.5 equals half speed
#define DISTANCE 150 //150 equals 150 inches
const float P = .02; //.02 equals 20 degrees full power.
const float DriveSpeed = .400;
AutonomousForward::AutonomousForward() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void AutonomousForward::Initialize() {
	Robot::driveTrain->GetPosition(startingLeft, startingRight);
//	Robot::driveTrain->Move(FORWARD_SPEED, FORWARD_SPEED);
	startingAngle = Robot::driveTrain->GetGyroAngle();
	
}
// Called repeatedly when this Command is scheduled to run
void AutonomousForward::Execute() {
	float errorAngle = startingAngle - Robot::driveTrain->GetGyroAngle();
	float speedAdjuster = errorAngle * P;
	float leftSpeed = DriveSpeed * (1 - speedAdjuster);
	float rightSpeed = DriveSpeed * (1 + speedAdjuster);
	
	Robot::driveTrain->Move(leftSpeed, rightSpeed);
	
	
	
}
// Make this return true when his Command no longer needs to run execute()
bool AutonomousForward::IsFinished() {
	float currentLeft = 0;
	float currentRight= 0;
	Robot::driveTrain->GetPosition(currentLeft, currentRight);
	if ((currentLeft - startingLeft > DISTANCE) && (currentRight - startingRight > DISTANCE))
			return true; //
	return false;
}
// Called once after isFinished returns true
void AutonomousForward::End() {
	Robot::driveTrain->Move(0, 0);
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousForward::Interrupted() {
}
