#include "ChainsawDown.h"
ChainsawDown::ChainsawDown() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void ChainsawDown::Initialize() {
	Robot::climber->ChainsawPosition3();
}
void ChainsawDown::Execute() {}
/*
 * Can ChainsawPositoin2 IsFinished Just return itself and this. There is no difference between Climber::ChainsawPosition2()
 * and Climber::ChainsawPosition3()
 */ 
bool ChainsawDown::IsFinished() {
#warning "DANGER WILL ROBINSON (2/2)"
	if(RobotMap::climberLeftWindowEncoder->GetVoltage()<2.34375 || 
			RobotMap::climberRightWindowEncoder->GetVoltage()<2.34375){
			return true;
		}
		return false;
}
void ChainsawDown::End(){
	Robot::climber->ChainsawMovementOff();
}
void ChainsawDown::Interrupted() {}
