#include "ChainsawDown.h"
#define BOTTOM_BUFFER 2.34375
ChainsawDown::ChainsawDown() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void ChainsawDown::Initialize() {
	Robot::climber->ChainsawDown();
}
void ChainsawDown::Execute() {}
bool ChainsawDown::IsFinished() {
#warning "DANGER WILL ROBINSON (2/2)"
	if(RobotMap::climberLeftWindowEncoder->GetVoltage()>BOTTOM_BUFFER || 
			RobotMap::climberRightWindowEncoder->GetVoltage()>BOTTOM_BUFFER){
			return true;
		}
		return false;
}
void ChainsawDown::End(){
	Robot::climber->ChainsawMovementOff();
}
void ChainsawDown::Interrupted() {}
