#include "ChainsawMiddle.h"
ChainsawMiddle::ChainsawMiddle() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void ChainsawMiddle::Initialize() {Robot::climber->ChainsawPosition2();}
void ChainsawMiddle::Execute() {}
bool ChainsawMiddle::IsFinished() {
	//Position 2 will only be accessable from position 1, not position 3
	if(RobotMap::climberRightWindowEncoder->GetVoltage()>1.25 || 
			RobotMap::climberRightWindowEncoder->GetVoltage()>1.25){
		return true;
	}
	else{
		return false;
	}
	
	//return Robot::climber->ClimberIsDown();
}
void ChainsawMiddle::End() {Robot::climber->ChainsawMovementOff();}
void ChainsawMiddle::Interrupted() {}
