#include "ChainsawUp.h"
#define TOP_BUFFER 0.15625
ChainsawUp::ChainsawUp() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void ChainsawUp::Initialize() {
	Robot::climber->ChainsawUp();
}
// Called repeatedly when this Command is scheduled to run
void ChainsawUp::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool ChainsawUp::IsFinished() {
#warning "DANGER WILL ROBINSON (1/2)"
	if(RobotMap::climberLeftWindowEncoder->GetVoltage()<TOP_BUFFER || 
			RobotMap::climberRightWindowEncoder->GetVoltage()<TOP_BUFFER){
		return true;
		}
		return false;
}
// Called once after isFinished returns true
void ChainsawUp::End() {
	Robot::climber->ChainsawMovementOff();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ChainsawUp::Interrupted() {
}
