#include "ClimberDrive.h"
ClimberDrive::ClimberDrive() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void ClimberDrive::Initialize() {}
void ClimberDrive::Execute() {
	Robot::climber->Climb(Robot::oi->getOperatorStick()->GetY());
}
bool ClimberDrive::IsFinished(){return false;}
void ClimberDrive::End(){}
void ClimberDrive::Interrupted() {}
