
#include "ClimberOn.h"
ClimberOn::ClimberOn() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
//TODO void ClimberOn::Initialize() {Robot::climber->EngageClimber();}
void ClimberOn::Execute() {}
bool ClimberOn::IsFinished() {return true;}
void ClimberOn::End() {}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ClimberOn::Interrupted() {
	ClimberOn::End();
}
