
#include "ClimberOff.h"
ClimberOff::ClimberOff() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void ClimberOff::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void ClimberOff::Execute() {
Robot::climber->DisengageClimber();
}
// Make this return true when this Command no longer needs to run execute()
bool ClimberOff::IsFinished() {return true;}
// Called once after isFinished returns true
void ClimberOff::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ClimberOff::Interrupted() {
	ClimberOff::End();
}
