#include "ClimberOff.h"
ClimberOff::ClimberOff() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void ClimberOff::Initialize() {}
void ClimberOff::Execute() {
	Robot::climber->DisengageClimber();
}
bool ClimberOff::IsFinished() {return true;}
void ClimberOff::End() {}
void ClimberOff::Interrupted() {}
