// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ClimberOn.h"
ClimberOn::ClimberOn() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void ClimberOn::Initialize() {Robot::climber->EngageClimber();}
void ClimberOn::Execute() {}
bool ClimberOn::IsFinished() {return true;}
void ClimberOn::End() {}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ClimberOn::Interrupted() {
	ClimberOn::End();
}
