#include "CollectDiscs.h"
CollectDiscs::CollectDiscs() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::collector);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void CollectDiscs::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void CollectDiscs::Execute() {
	//will need some logic somewhere to provide for toggling (press once for on, press again for off)
}
// Make this return true when this Command no longer needs to run execute()
bool CollectDiscs::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void CollectDiscs::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CollectDiscs::Interrupted() {
}
