#include "JoystickDrive.h"
#include "../Subsystems/DriveTrain.h"

JoystickDrive::JoystickDrive() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void JoystickDrive::Initialize() {
	printf("JoystickDriveInitializeMethod\n");
}
// Called repeatedly when this Command is scheduled to run
void JoystickDrive::Execute() {
	Robot::driveTrain->Move();
	printf("JoystickDriveExecuteMethod\n");
}
// Make this return true when this Command no longer needs to run execute()
bool JoystickDrive::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void JoystickDrive::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void JoystickDrive::Interrupted() {
}
