#warning Untested 
#include "SetCubicDrive.h"
SetCubicDrive::SetCubicDrive() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void SetCubicDrive::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void SetCubicDrive::Execute() {
	if (Robot::driveTrain->IsCubic()){
		Robot::driveTrain->CubicOnOff(false);
	}
	else
		Robot::driveTrain->CubicOnOff(true);
}
// Make this return true when this Command no longer needs to run execute()
bool SetCubicDrive::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void SetCubicDrive::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetCubicDrive::Interrupted() {
}
