#include "SetChainsawPosition2.h"
SetChainsawPosition2::SetChainsawPosition2() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void SetChainsawPosition2::Initialize() {Robot::climber->ChainsawPosition2();}
void SetChainsawPosition2::Execute() {}
//will overshoot 99% of the time!
bool SetChainsawPosition2::IsFinished() {return Robot::climber->ClimberIsDown();}
void SetChainsawPosition2::End() {Robot::climber->ChainsawMovementOff();}
void SetChainsawPosition2::Interrupted() {}
