#include "SetChainsawPosition3.h"
SetChainsawPosition3::SetChainsawPosition3() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void SetChainsawPosition3::Initialize() {
	Robot::climber->ChainsawPosition3();
}
void SetChainsawPosition3::Execute() {}
/*
 * Can ChainsawPositoin2 IsFinished Just return itself and this. There is no difference between Climber::ChainsawPosition2()
 * and Climber::ChainsawPosition3()
 */ 
bool SetChainsawPosition3::IsFinished() {
	if(RobotMap::climberChainsawBottomSwitch->IsPressed()){
			return true;
		}
		return false;
}
void SetChainsawPosition3::End(){
	Robot::climber->ChainsawMovementOff();
}
void SetChainsawPosition3::Interrupted() {}
