#include "ShooterOff.h"
ShooterOff::ShooterOff() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void ShooterOff::Initialize() {
	Robot::shooter->ShooterOff();
	
}
// Called repeatedly when this Command is scheduled to run
void ShooterOff::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool ShooterOff::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void ShooterOff::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterOff::Interrupted() {
}
