// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "shooterAdjustAngle.h"
#define DEADZONE 0.2
ShooterAdjustAngle::ShooterAdjustAngle() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void ShooterAdjustAngle::Initialize() {
	printf ("ShooterAdjustAngle started...\n");
}
// Called repeatedly when this Command is scheduled to run
void ShooterAdjustAngle::Execute() {
	//float hatx = Robot::oi->getOperatorStick()->GetAxis(5)
	//float left = Robot::oi->getLeftStick()->GetY(GenericHID::kLeftHand);
	//int hat = Robot::oi->getOperatorStick()->GetAxis(5);
	//float hat = Robot::oi->getOperatorStick()->GetButton(Joystick::kTopButton);
	//printf ("shooterAdjustAngle::Execute hat value is %f\n", hat);
	float hat = 0.0f;
	int adjustment = Robot::shooter->GetFineAdjustmentAngle();
	if (hat > DEADZONE){
		Robot::shooter->IncrementAngle(adjustment);
	}
	else if (hat < -DEADZONE){
		Robot::shooter->IncrementAngle(-1 * adjustment);	
	}	
}
// Make this return true when this Command no longer needs to run execute()
bool ShooterAdjustAngle::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void ShooterAdjustAngle::End() {
	printf ("ShooterAdjustAngle ended\n");
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterAdjustAngle::Interrupted() {
	printf ("ShooterAdjustAngle interruptingcow\n");
}
