#include "ShooterOn.h"
ShooterOn::ShooterOn() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void ShooterOn::Initialize() {
	Robot::shooter->ShooterOn();
}
// Called repeatedly when this Command is scheduled to run
void ShooterOn::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool ShooterOn::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void ShooterOn::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterOn::Interrupted() {
}
