#include "ShooterOff.h"
ShooterOff::ShooterOff() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void ShooterOff::Initialize() {Robot::shooter->ShooterOnOff(false);}
void ShooterOff::Execute() {}
bool ShooterOff::IsFinished() {return true;}
void ShooterOff::End() {}
void ShooterOff::Interrupted() {}
