// RobotBuilder Version: 0.0.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "SmartDashboard/SmartDashboard.h"
#include "TestSmartDashboard.h"
int TestSmartDashboard::testValue = 1;
TestSmartDashboard::TestSmartDashboard() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void TestSmartDashboard::Initialize() {
	
	testValue = testValue + 1;
}
// Called repeatedly when this Command is scheduled to run
void TestSmartDashboard::Execute() {
	
	SmartDashboard::PutNumber("Test Value", testValue);
	printf("TestSmartDashboard Command is executed. %d\n", testValue);
	
}
// Make this return true when this Command no longer needs to run execute()
bool TestSmartDashboard::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void TestSmartDashboard::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TestSmartDashboard::Interrupted() {
}
