#warning Untested
#include "TurboDrive.h"
#include "../Subsystems/DriveTrain.h"
TurboDrive::TurboDrive() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void TurboDrive::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void TurboDrive::Execute() {
	Robot::driveTrain->TurboOnOff(true);
}
// Make this return true when this Command no longer needs to run execute()
bool TurboDrive::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void TurboDrive::End() {
	Robot::driveTrain->TurboOnOff(false);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TurboDrive::Interrupted() {
}
