#include "WriteDriveData.h"
int WriteDriveData::count = 0;
const char * WriteDriveData::name = "DriveData.csv";WriteDriveData::WriteDriveData() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	file = fopen(name, "w+");
	fprintf(file, "Left Encoder Speed, Left Encoder Voltage, Left Encoder Current, " +
			"Right Encoder Speed, Right Encoder Voltage, Right Encoder Current, " +
			"Battery Voltage, Gyro Angle\n");
	fclose(file);
}
void WriteDriveData::Initialize() {
	
}
void WriteDriveData::Execute() {}
bool WriteDriveData::IsFinished() {return true;}
void WriteDriveData::End() {}
void WriteDriveData::Interrupted() {}
