#ifndef ALLIGNMENTDATA_H
#define ALLIGNMENTDATA_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
class AllignmentData: public Subsystem {
private:
	static int DEFAULT;
	double calculatedDistance;
	double calculatedAngle;
	NetworkTable* trackingDataTable;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	AllignmentData();
	void InitDefaultCommand();
	double GetCalculatedDistance();
	double GetCalculatedAngle();
	bool IsTarget();
};
#endif
