#include "AllignmentData.h"
#include "../Robotmap.h"
#include "../Commands/PullNewAllignmentData.h"
int AllignmentData::DEFAULT = -1;
AllignmentData::AllignmentData() : Subsystem("AllignmentData") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	calculatedDistance = DEFAULT;
	calculatedAngle = DEFAULT;
	trackingDataTable = NetworkTable::GetTable("tracking");
}
void AllignmentData::InitDefaultCommand(){SetDefaultCommand(new PullNewAllignmentData());}
double AllignmentData::GetCalculatedAngle() {return calculatedAngle;}
double AllignmentData::GetCalculatedDistance() {return calculatedDistance;}
bool AllignmentData::IsTarget(){return calculatedDistance != DEFAULT && calculatedAngle != DEFAULT;}
void AllignmentData::Refresh(){
	//begin transaction...
	calculatedDistance = trackingDataTable->GetNumber("calculatedDistance", -1);
	calculatedAngle = trackingDataTable->GetNumber("calculatedAngle", -1);
	//end transaction...
}
