#include "AllignmentData.h"
#include "../Robotmap.h"
int AllignmentData::DEFAULT = -1;
AllignmentData::AllignmentData() : Subsystem("AllignmentData") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	calculatedDistance = DEFAULT;
	calculatedAngle = DEFAULT;
	trackingDataTable = NetworkTable::GetTable("tracking");
}
void AllignmentData::InitDefaultCommand(){}
double AllignmentData::GetCalculatedDistance() {return trackingDataTable->GetNumber("calculatedAngle", -1);}
bool AllignmentData::IsTarget(){return calculatedDistance != DEFAULT && calculatedAngle != DEFAULT;}
