#ifndef ALLIGNMENTDATA_H
#define ALLIGNMENTDATA_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
class AllignmentData: public Subsystem {
private:
	int calculatedDistance;
	int calculatedAngle;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	AllignmentData();
	int GetCalculatedDistance();
	int GetCalculatedAngle();
	void SetCalculatedDistance(int calculatedDistance);
	void SetCalculatedAngle(int calculatedAngle);
};
#endif
