#include "Climber.h"
#include "../RobotMap.h"
#include "../Robot.h"
#include "../Commands/ClimberDrive.h"
#include "../WPILibExtensions/WPILibExtensions.h"
Climber::Climber() : Subsystem("Climber") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftClimbWindowTalon = RobotMap::climberLeftClimbWindowTalon;
	rightClimbWindowTalon = RobotMap::climberRightClimbWindowTalon;
	leftCIM = RobotMap::climberLeftCIM;
	rightCIM = RobotMap::climberRightCIM;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftWindowEncoder = RobotMap::climberLeftWindowEncoder;
	rightWindowEncoder = RobotMap::climberRightWindowEncoder;
	ClimberOnOff = false;
}
    
void Climber::InitDefaultCommand() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Climber::ClimberJagConfig(){
	leftCIM->ChangeControlMode(CANJaguar::kSpeed);
	leftCIM->SetSpeedReference(CANJaguar::kSpeedRef_Encoder);
	leftCIM->ConfigEncoderCodesPerRev(360);
	leftCIM->EnableControl();
	rightCIM->ChangeControlMode(CANJaguar::kSpeed);
	rightCIM->SetSpeedReference(CANJaguar::kSpeedRef_Encoder);
	rightCIM->ConfigEncoderCodesPerRev(360);
	rightCIM->EnableControl();
	
}
void Climber::Climb(float yPosition){
	if(ClimberOnOff){
		leftCIM->Set(yPosition);
		rightCIM->Set(yPosition);
	}
	else{
		leftCIM->Set(0);
		rightCIM->Set(0);	
	}
}
bool Climber::getClimberOnOff(){
	return ClimberOnOff;
}	
void Climber::EngageClimber(){
	//printf("\n\n *****In engage *******\n\n");
	ClimberOnOff=true;
}	
void Climber::DisengageClimber(){
	//printf("\n\n *****In disengage *******\n\n");
	ClimberOnOff=false;
}
void Climber::ChainsawMovementOff(){
	leftClimbWindowTalon->Set(0);
	rightClimbWindowTalon->Set(0);
	
}
//What does Position 1 Mean?
void Climber::ChainsawUp(){
	leftClimbWindowTalon->Set(CHAINSAW_UP_SPEED);
	rightClimbWindowTalon->Set(CHAINSAW_UP_SPEED);
}
//What Does Position 2  Mean?
void Climber::ChainsawDown(){
	leftClimbWindowTalon->Set(CHAINSAW_DOWN_SPEED);
	rightClimbWindowTalon->Set(CHAINSAW_DOWN_SPEED);
}
