#include "DriveTrain.h"
#include "../Robotmap.h"
#include "../Commands/JoystickDrive.h"
#include "../OI.h"
#define MAXJAGSPEED 2500
DriveTrain::DriveTrain() : Subsystem("DriveTrain") {
	left = Robot::oi->getLeftStick();
	right = Robot::oi->getRightStick();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftDriveMotor = RobotMap::driveTrainLeftDriveMotor;
	rightDriveMotor = RobotMap::driveTrainRightDriveMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void DriveTrain::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new JoystickDrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void DriveTrain::Move(){ 
	//creates ratio between y-value of joystick and jag speed
	leftDriveMotor->Set(MAXJAGSPEED * left->GetY());
	rightDriveMotor->Set(MAXJAGSPEED * right->GetY());
}
