#include "DriveTrain.h"
#include "../Robotmap.h"
#include "../Commands/JoystickDrive.h"
#include "../OI.h"
#include "GenericHID.h"
//#define  DEBUGDRIVETRAIN
DriveTrain::DriveTrain() : Subsystem("DriveTrain") {
	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftDriveMotor = RobotMap::driveTrainLeftDriveMotor;
	rightDriveMotor = RobotMap::driveTrainRightDriveMotor;
	driveTrainGyro = RobotMap::driveTrainDriveTrainGyro;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void DriveTrain::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new JoystickDrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void DriveTrain::Move(float left, float right){ 
#ifdef DEBUGDRIVETRAIN
	printf("calling move\n");
#endif
	//writes y-value of joystick to jag 
	leftDriveMotor->Set(left);
	rightDriveMotor->Set(right);
#ifdef DEBUGDRIVETRAIN	
	printf("Left Y: %f  Right Y: %f\n", left, right);
	printf("Left M: %f  Right M: %f\n", leftDriveMotor->Get(), rightDriveMotor->Get());
#endif
}
