#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
class DriveTrain: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANJaguar* leftDriveMotor;
	CANJaguar* rightDriveMotor;
	Gyro* driveTrainGyro;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DriveTrain();
	void InitDefaultCommand();
	void Move();
	float GetDriveVoltage(bool left);
	float GetDriveCurrent(bool left);
	float GetDriveSpeed(bool left);
	float GetGyroAngle();
private:
	Joystick *left, *right;
};
#endif
