#include "Shooter.h"
#include "../Robotmap.h"
Shooter::Shooter() : Subsystem("Shooter") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	elevationJag = RobotMap::shooterElevationJag;
	elevationEncoder = RobotMap::shooterElevationEncoder;
	shooterJag = RobotMap::shooterShooterJag;
	shooterEncoder = RobotMap::shooterShooterEncoder;
	elevatorTopSwitch = RobotMap::shooterElevatorTopSwitch;
	elevatorBottomSwitch = RobotMap::shooterElevatorBottomSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
void Shooter::InitDefaultCommand() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Shooter :: ShooterOn(){
	shooterJag->Set(speed);
}
void Shooter::ShooterOff(){
	shooterJag->Set(SHOOTER_OFF);
}
int Shooter::GetSetSpeed() {return speed;}
int Shooter::GetSetElevationAngle() {return elevationAngle;}
int Shooter::GetDefaultSpeed() {return defaultSpeed;}
int Shooter::GetDefaultElevationAngle() {return defaultElevationAngle;}
void Shooter::SetToDefaults(){
	speed = defaultSpeed;
	elevationAngle = defaultElevationAngle;
}
void Shooter::UpdateDefaults(int distanceToTarget, int robotAngleToTarget){
	//TODO: Math
}
void Shooter::IncrementSpeed(int speedIncrement){
	speed += speedIncrement;
}
void Shooter::IncrementAngle(int angleIncrement){
	elevationAngle += angleIncrement;
}
//Figured this might be useful if we want to quickly put the speed to a certain preset
void Shooter::SetRawSpeed(int speed) {
	if(speed < 0 ) return;
	this->speed = speed;
}
bool Shooter::IsUpLimitPressed(){
	return elevatorTopSwitch->Get() == 1;
}
bool Shooter::IsDownLimitPressed(){
	return elevatorBottomSwitch->Get() == 1;
}
//TODO: Update with something realistic
int Shooter::GetFineAdjustmentSpeed() {return 20;}
int Shooter::GetCoarseAdjustmentSpeed() {return 200;}
