#include "Shooter.h"
#include "../Robotmap.h"

Shooter::Shooter() : Subsystem("Shooter") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	shooterJag = RobotMap::shooterShooterJag;
	shooterEncoder = RobotMap::shooterShooterEncoder;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Shooter::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Shooter :: ShooterOn(){
	shooterJag->Set(SHOOTER_SPEED);
}

void Shooter::ShooterOff(){
	shooterJag->Set(SHOOTER_OFF);
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

